config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  
  resources :users

  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments

  validates :name, presence: true

  def average_rating
    comments.average(:rating).to_f
  end

  def price_in_cents
    (price * 100).to_i
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource
  respond_to :json, :html
  include ProductsHelper

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.development? == true
        puts "test console"
        logger.debug "search for #{search_term}"
        @products = Product.where("sold_date is null AND name LIKE ?", "%#{search_term}%").paginate(page: params[:page], per_page: 4)
        logger.debug "showing products matching #{search_term}"
      else
        @products = Product.where("sold_date is null AND name ilike ?", "%#{search_term}%").paginate(page: params[:page], per_page: 4)
      end
    else
      @products = Product.where("sold_date is null").paginate(page: params[:page], per_page: 4)
      logger.debug "showing all unsold products"
    end
    respond_with @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # @comments = @product.comments.all.paginate(page: params[:page], per_page: 5).order("created_at DESC")
    fetch_comments
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :product_year, :sold_date, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def cache_key_for_products
    count = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end

  def fetch_comments
    comments = $redis.get("comments")
    if comments.nil?
      comments = @product.comments.all.to_json
      $redis.set("comments", comments)
      # Expire the cache, every 5 hours
      $redis.expire("comments",5.hour.to_i)
    end
    @comments = JSON.load comments
  end

end

app/views/products/_comments.html.erb

  <div class="product-reviews col-xs-12">
    <% @comments.each do |comment| %>
      <div class="row">
        <hr>
        <p>
 
          <% if signed_in? && current_user.admin? %>
            <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>
        <% logger.debug "Displaying rating #{comment["rating"]}" %>
        <div class="rated" data-score="<%= comment["rating"] %>"></div>
        <p><%= comment["body"]%></p>
      </div>
    <% end %>

  </div>

app/views/products/_form.html.erb
<div>
  <%= form_for @product, :html => {class: "col-xs-12 col-md-8"} do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
 
    <div class="panel panel-primary">
      <div class="panel-body">
        <div class="form-group col-sm-6">
          <div class="col-xs-12">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="form-group col-sm-6">
          <div class="col-xs-12">
            <%= f.label :product_year %><br>
            <%= f.number_field :product_year, class: "form-control" %>
          </div>
        </div>
        <div class="form-group col-sm-6">
          <div class="col-xs-12">
            <%= f.label :description %><br>
            <%= f.text_area :description, class: "form-control" %>
          </div>
        </div>
        <div class="form-group col-sm-6">
          <div class="col-xs-12">
            <%= f.label :price %><br>
            <%= f.number_field :price, class: "form-control" %>
          </div>
        </div>
        <div class="form-group col-sm-6">
          <div class="col-xs-12">
            <%= f.label :image_url %><br>
            <%= f.text_field :image_url, class: "form-control" %>
          </div>
        </div>
        <div class="form-group col-sm-6">
          <div class="col-xs-12">
            <%= f.label :sold_date %><br>
            <%= f.date_field :sold_date, class: "form-control" %>
          </div>
        </div>
        <div class="form-group col-sm-6">
          <div class="col-xs-12">
            <%= f.label :color %><br>
            <%= f.select :colour, ['red', 'yellow', 'green', 'blue', 'black', 'white'], { include_blank: true } , {class: "form-control"} %>
          </div>
        </div>
        <div class="form-group col-sm-6">
          <div class="col-xs-12">
            <div class="actions">
              <%= f.submit 'Update Product', class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/products/_new_comment.html.erb

<% if signed_in? %>
  <div class="panel panel-default comment">
    <div class="panel-heading">
      <h4>Add a review:</h4>
    </div>
    <div class="panel-body">
      <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
        <div class="form-group">
          <div class="rating">
            <%= f.label "Rating" %><br>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :body, "Comments" %><br>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <p>
          <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/_product.html.erb

<% cache product do %>
  <div class="item col-sm-6 col-md-3">
    <%= link_to "/products/" + product.id.to_s do %>
      <%= image_tag(product.image_url, class: "img-responsive") %>
    <% end %>
    <h2><%= product.name %></h2>
    <% logger.debug "Showing product: #{product.name}" %>
    <p class="description"><%= product.description %></p>
    <p class="price"><%= number_to_currency product.price, precision: 2 %></p>
  </div>
<% end %>



app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<div class="col-sm-12">
  <%= link_to 'Show', @product, type: "button", class: "btn btn-default" %>
  <%= link_to 'Back', products_path, type: "button", class: "btn btn-default" %>
</div>

app/views/products/index.html.erb
<h1>Products available:</h1>

<%# paragraph_number = 1 %>
<%# 5.times do %>
  <!-- <p>This is paragraph number <%# paragraph_number %></p> 
  <%# paragraph_number = paragraph_number + 1 %> -->
<%# end %>
<div class="container-fluid">
  <div class="row">
    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>
  </div>
</div>
<%= will_paginate @products %>
<br>

<div class="col-sm-12">
  <%= link_to 'New Product', new_product_path, type: "button", class: "btn btn-default" %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<div class="col-sm-12">
  <%= link_to 'Back', products_path, type: "button", class: "btn btn-default" %>
</div>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="col-md-5 col-sm-6 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <% cache @product do %>
          <div class="item">
            <%= image_tag(@product.image_url, class: "img-responsive img-zoom", data: { zoom_image: '/assets/' + @product.image_url}) %>
          </div>

          <div class="panel-footer">
            <div class="row">
              <h3 class="col-xs-9"><%= @product.name %></h3>
              <p class="col-xs-3 price"><%= number_to_currency @product.price, precision: 2 %>
              <a href="#"><span class="glyphicon glyphicon-map-marker"></span></a></p>
            </div>
            <p class="description"><%= @product.description %></p>
            <div class="row">
              <p class="col-xs-12">Average Rating: 
                <div class="rated col-xs-12" data-score="<%= @product.average_rating %>"></div>
              </p>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <%= form_tag "/payments/create" do %>
      <%= render partial: 'shared/stripe_checkout_button' %>
      <%= hidden_field_tag(:product_id, @product.id) %>
    <% end %>

    <%= render 'new_comment' %>
    <%= render 'comments' %>

    <div class="editback">
      <%= link_to 'Edit', edit_product_path(@product), type: "button", class: "btn btn-default" %>
      <%= link_to 'Back', products_path, type: "button", class: "btn btn-default" %>
    </div>
  </div>
</div>