config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  
  resources :users

  resources :products do
    resources :comments
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Appcf</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page-wrap">
  <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <a class="navbar-brand" href="#">
        <img alt="brand" src="/assets/bb-small.jpg">
      </a>
      <!--end projectName -->
      </div> <!--end navbar-header -->
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Home", root_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        
          <li class= "nav-item"><%= link_to "Sales", "#Sales", class: "nav-link" %></li>
          <li class= "nav-item"><%= link_to "Contact", static_pages_contact_path, class: "nav-link" %></li>
          <li class= "nav-item"><%= link_to "Products", products_path, class: "nav-link" %></li>
          <li class= "nav-item"><%= form_tag("/products", method: "get", class: "navbar-form navbar-right", role: "search") do %>
       
          <div class="form-group">
            <%= label_tag(:q, "Search for:", class: "nav-item") %>
            <%= text_field_tag :q, params[:q], class: "form-control form-control-sm", type: "search"%>
          </div>
          <%= submit_tag "Search", class: "btn btn-default" %>
          <% end %></li> 
        </ul>
        <ul class="nav navbar-nav pull-right">
          <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "nav-item") %>
          <% else %>
            <%= link_to('Login', new_user_session_path, class: "nav-item") %>
          <% end %>
          </li>
        </ul>
      </div> <!--end navbar-collapse -->
    </div> <!--end container-fluid  -->
  </nav>
  <% if notice %>
    <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p id="alert" class="alert alert-warning" role="alert"><%= alert %></p>
  <% end %>
  <div class="static-page">
    <%= yield %>
  </div>
</div>

<footer class="site-footer">
  <p>&copy; 2015 Bike Berlin</p>
</footer>

</body>
</html>